# Generated by Django 4.1 on 2024-07-13 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('speak_lang', models.CharField(choices=[('japanese', 'Japanese'), ('english', 'English'), ('chinese', 'Chinese')], max_length=50, null=True)),
                ('it_lang', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('javascript', 'JavaScript'), ('java', 'JavaScript')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
